# Generated by Django 3.2.8 on 2021-10-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='akbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('discription', models.TextField()),
                ('rating', models.IntegerField()),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
    ]
